from .user import User as UserResource
from .user import Users as UsersResource
from .pedidos import Pedidos as PedidosResource
from .pedidos import Pedido as PedidoResource
from .valoraciones import Valoracion as ValoracionResource
from .valoraciones import Valoraciones as ValoracionesResource
from .notificaciones import Notificaciones as NotificacionResource
from .producto import Producto as ProductoResource
from .producto import Productos as ProductosResource
from .producto import ResumenProducto as ResumenProductoResource
from .asignaciones import Asignacion as AsignacionResource
